---
title: "Algoritma FP-Growht dengan R"
date: "`r Sys.Date()`"
author: ayu safitri-Institut Teknologi Statistika dan Bisnis Muhammadiyah
output:
  rmdformats::readthedown:
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    highlight: tango
bibliography: references.bib
---
# Algoritma Fp-Growht
FP-Growth adalah salah satu alternatif algoritma yang dapat digunakan untuk menentukan himpunan data yang paling sering muncul (frequent itemset) dalam sebuah kumpulan data (Indah Mulia Sari : 2013).
FP-Growth adalah algoritma pencarian frequent item sets yang didapat dari FP-tree dengan menjelajahi tree dari bawah menuju ke atas (Tan, Steinbach, & Kumar, 2004).
FP-growth adalah salah satu alternatif algoritma yang dapat digunakan untuk menentukan himpunan data yang paling sering muncul (frequent itemset) dalam sebuah kumpulan data. FP-growth menggunakan pendekatan yang berbeda dari paradigma yang digunakan pada algoritma Apriori (Sensuse, 2012).

Jadi dapat disimpulkan bahwa FP-Growth adalah salah satu algoritma yang digunakan untuk mencari himpunan data yang sering muncul dari sekumpulan data, dengan menggunakan cara pembangktan stuktur data Tree.

# Tahapan Algoritma Fp-Growht
Siapkan Dataset
Pengurutan berdasarkan nilai frekuensi kemunculan item yang terbesar
Membentuk FP-tree 
Membentuk Conditional Pattern Base
Membentuk Conditional FP-tree
Membentuk Frequent Pattern Generated
Mencari frequency 2 Itemset
Mencari Support 2 Itemset
Mencari Confidance 2 Itemset

# Eksperimen Algoritma
disini saya akan menggunakan dataset Online Retail.

## Library
```{r}

```

